name: Saynaa Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Make
      run: make

    - name: Test
      run: ./saynaa example.sa

    - name: App Test
      run: ./app
